#!/bin/bash
cd area51
export LD_LIBRARY_PATH=devmem/CLib
banner AREA51
./yv2_parse.py

export phys_addr="/sys/class/udmabuf/udmabuf0/phys_addr"
if [ ! -e "$phys_addr" ]; then
    insmod /area51/udmabuf/udmabuf.ko udmabuf0=304128
fi

python ./devmem/CLib/cam_demo.py -k 120

